# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.0"
stylua = "JohnnyMorganz/stylua@0.19.1"