[package]
name = "data-oriented-house/lemonsignal"
version = "1.9.0"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["Aspecky", "Sona"]

description = "A pure Luau signal implementation faster than most other implementations in Roblox."

realm = "shared"

exclude = ["README.md", "build"]

[dependencies]